development:
  adapter: mysql
  encoding: utf8
  database: EscuelaApp_development
  pool: 5
  username: root
  password: megapanza17
test:
  adapter: mysql
  encoding: utf8
  database: EscuelaApp_test
  pool: 5
  username: root
  password: megapanza17
production:
  adapter: mysql
  encoding: utf8
  database: EscuelaApp_production
  pool: 5
  username: root
  password: megapanza17